### ISSUE TITLE
TronNet suddenly stop working !

### ISSUE THREAD

**Issue by daustany** [stoway/TronNet#16]
It was working, suddenly has stopped with no reason !

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter "Illegal character ‏ at 0")
at TronNet.Crypto.Base58Encoder.Decode(String input)
at TronNet.Crypto.Base58Encoder.DecodeFromBase58Check(String addressBase58)
at TronNet.Contracts.TRC20ContractClient.TransferAsync(String contractAddress, ITronAccount ownerAccount, String toAddress, Decimal amount, String memo, Int64 feeLimit)

**Comment by daustany** [comment]
Grpc.Core.RpcException: 'Status(StatusCode="Unknown", Detail="Stream removed")'

**Comment by daustany** [comment]
I found the problem.
To inform colleagues who may encounter this problem:

In the system I have implemented, the user has the ability to transfer tokens from one wallet to another.
Therefore, it must enter the destination wallet address.
The problem with my work in this section was that I did not check the accuracy of the destination wallet address before requesting a transfer.
And one of the users had entered the wallet address, which was correct in appearance but had a different encoding in terms of characters! That's why it was a little difficult for me to find the cause of the error.

This was incorrect: _(The encoding address may have been modified when pasting)_
‏TR1Q4Gr5JMwfQVh9ZDUXLo6ewcYYkTbP7J

And this is correct wallet address:
TR1Q4Gr5JMwfQVh9ZDUXLo6ewcYYkTbP7J

Given this explanation, make sure the wallet address is correct before sending any request to the blockchain network.
For example, you can use the following code. _(I have not yet found the gRPC equivalent command on TronNet due to the rush to resolve the issue, but the following code snippet may be helpful)_

```
        public class AddressValidation
        {
            public bool result { get; set; }
            public string message { get; set; }
        }

        public async Task<bool> IsTRC20Wallet(string walletAddress)
        {
            var client = new RestClient("https://api.trongrid.io/wallet/validateaddress");
            var request = new RestRequest(Method.POST);
            request.AddHeader("Accept", "application/json");
            request.AddHeader("Content-Type", "application/json");
            request.AddParameter("application/json", "{\"address\":\"" + walletAddress + "\"}", ParameterType.RequestBody);
            IRestResponse response = await client.ExecuteAsync(request);

            if (response.IsSuccessful)
            {
                AddressValidation addressValidation = JsonConvert.DeserializeObject<AddressValidation>(response.Content);

                return addressValidation.result;
            }
            else
                return false;
        }
```
