### ISSUE TITLE
在VS中发布时选择生成单个文件，运行时会报异常

### ISSUE THREAD

**Issue by helloben1980** [stoway/TronNet#25]
在VS中发布时选择生成单个文件，运行时会报异常
查找相关资料，是引用的GRPC包引起的，在更新的GRPC版本中修复了该问题
System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()

**Comment by stoway** [comment]
好的，谢谢分享！
