### ISSUE TITLE
Transfer trc20 token

### ISSUE THREAD

**Issue by MRayp** [stoway/TronNet#3]
How can i transfer TRC-20 tokens ? does this project support them ?

**Comment by stoway** [comment]
not yet, need time.

**Comment by MRayp** [comment]
any update? there is a pending pull request about " add trc20 contract token module "

**Comment by qaibeibei** [comment]
Can trc20 be transferred？ Online etc.

**Comment by stoway** [comment]
submit at the end of this month.

**Comment by stoway** [comment]
see: https://github.com/stoway/TronNet/tree/dev#sample-3-contract-trc20-transfer-usdt

**Comment by xclud** [comment]
I get this exception:

```
fail: TronNet.Contracts.TRC20ContractClient[0]
      Specified argument was out of the range of valid values. (Parameter 'index')
      System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
         at Google.Protobuf.Collections.RepeatedField`1.get_Item(Int32 index)
         at TronNet.Contracts.TRC20ContractClient.GetDecimals(WalletClient wallet, Byte[] contractAddressBytes)
         at TronNet.Contracts.TRC20ContractClient.TransferAsync(String contractAddress, ITronAccount ownerAccount, String toAddress, Decimal amount, String memo, Int64 feeLimit)
```
